# .github/workflows/second-workflow.yml
name: Second Workflow (Triggered by First)

on:
  push:
    branches:
      - develop

jobs:
  triggered-job:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm trigger
        run: |
          echo "✅ Triggered by First Workflow!"
